[package]
name = "simpleirc"
version = "0.1.0"
authors = ["Filip Szczepa≈Ñski <jazz2rulez@gmail.com>"]

[dependencies]
irc = "0.11.3"
chrono = "0.2"
termion = "1.1.4"
rustyline = "1.0.0"
unicode-width = "0.1.4"
